#!/usr/bin/env bash
set -Eeuo pipefail

ETC=/etc/proxy-pool
AWG_STATE_DIR=$ETC/awg-nodes
DP_STATE_DIR=$ETC/dataplane-nodes
BACKUP_ROOT=/var/lib/proxy-pool/dataplane-nodes
TELEMT_CONFIG_DEFAULT=/etc/telemt/telemt.toml
HAPROXY_CONFIG=/etc/haproxy/haproxy.cfg

red(){ printf '\033[31m%s\033[0m\n' "$*" >&2; }
green(){ printf '\033[32m%s\033[0m\n' "$*"; }
yellow(){ printf '\033[33m%s\033[0m\n' "$*" >&2; }
cyan(){ printf '\n\033[1;36m== %s ==\033[0m\n' "$*"; }
getenv_file(){ sed -n "s/^$2=//p" "$1" 2>/dev/null | tail -n1 | sed -e 's/^"//' -e 's/"$//' -e "s/^'//" -e "s/'$//"; }
yesno(){ local p="$1" v=''; read -r -p "$p [y/N]: " v </dev/tty || true; [[ "$v" =~ ^[yY]$ ]]; }

[[ $EUID -eq 0 ]] || { red 'Запустите через sudo/root.'; exit 1; }

require_enter(){
  [[ -r $ETC/settings.env ]] || { red 'TYXE Controller не найден.'; exit 1; }
  [[ "$(getenv_file "$ETC/settings.env" PROXY_POOL_ROLE)" == controller ]] || { red 'tyxe-dataplane нужно запускать на ENTER/controller.'; exit 1; }
  install -d -m 700 "$DP_STATE_DIR" "$BACKUP_ROOT"
}

choose_awg_state(){
  local requested="${1:-}" count
  if [[ -n "$requested" ]]; then
    AWG_STATE="$AWG_STATE_DIR/$requested.state"
    [[ -r $AWG_STATE ]] || { red "AWG state не найден: $requested"; return 1; }
    return 0
  fi
  mapfile -t states < <(find "$AWG_STATE_DIR" -maxdepth 1 -type f -name '*.state' -printf '%f\n' 2>/dev/null | sort)
  count=${#states[@]}
  (( count > 0 )) || { red 'Не найдено настроенных AWG-нoden.'; return 1; }
  if (( count == 1 )); then AWG_STATE="$AWG_STATE_DIR/${states[0]}"; return 0; fi
  printf 'AWG-ноды:\n'; printf '  %s\n' "${states[@]%.state}"
  red 'Укажите node id: tyxe-dataplane setup <id>'
  return 1
}

load_awg(){
  choose_awg_state "${1:-}" || return 1
  # Root-owned state generated by tyxe-awg; shell-compatible values are escaped with %q.
  # shellcheck disable=SC1090
  . "$AWG_STATE"
  : "${NODE_ID:?}" "${EXIT_HOST:?}" "${EXIT_IP:?}" "${ENTER_IP:?}" "${LOCAL_IF:?}"
  SSH_PORT=${SSH_PORT:-22}
  SSH_KEY=${SSH_KEY:-}
  TARGET="root@$EXIT_HOST"
  SSH=(-p "$SSH_PORT" -o ConnectTimeout=10 -o ServerAliveInterval=15 -o ServerAliveCountMax=2 -o ControlMaster=auto -o ControlPersist=120 -o ControlPath=/run/tyxe-dataplane-%C)
  if [[ -n $SSH_KEY ]]; then SSH+=(-i "$SSH_KEY"); fi
  return 0
}
rx(){ ssh "${SSH[@]}" "$TARGET" "$@"; }
rscript(){ ssh "${SSH[@]}" "$TARGET" 'bash -s'; }

find_telemt_config(){
  TELEMT_CONFIG=$(rx "python3 - <<'PY'
from pathlib import Path
cands=[Path('/etc/telemt/telemt.toml'),Path('/etc/telemt.toml')]
for p in cands:
    if p.is_file():
        print(p); raise SystemExit
raise SystemExit(1)
PY") || { red 'Telemt config на EXIT не найден.'; return 1; }
}

preflight(){
  cyan 'Preflight'
  [[ -d /sys/class/net/$LOCAL_IF ]] || { red "AWG interface $LOCAL_IF не поднят на ENTER."; return 1; }
  ping -c 2 -W 2 "$EXIT_IP" >/dev/null || { red "EXIT $EXIT_IP недоступен через AWG."; return 1; }
  rx 'id -u' | grep -qx 0 || { red 'Нужен root SSH на EXIT.'; return 1; }
  rx "systemctl is-active awg-quick@awg0.service >/dev/null" || { red 'AWG на EXIT не active.'; return 1; }
  rx "systemctl is-active telemt >/dev/null" || { red 'Telemt на EXIT не active.'; return 1; }
  find_telemt_config
  if rx "grep -Eq '^\\s*\\[\\[server\\.listeners\\]\\]' '$TELEMT_CONFIG'"; then
    red 'В Telemt есть активный [[server.listeners]]. Автопатч намеренно остановлен, чтобы не переопределить пользовательские listeners.'
    red "Проверьте: grep -nE '^\\s*\\[\\[server\\.listeners\\]\\]|^\\s*(ip|announce|announce_ip)\\s*=' $TELEMT_CONFIG"
    return 1
  fi
  local holder
  holder=$(ss -ltnpH 'sport = :443' 2>/dev/null || true)
  if [[ -n $holder ]] && ! grep -q 'haproxy' <<<"$holder"; then
    red 'TCP/443 на ENTER уже занят:'; printf '%s\n' "$holder" >&2; return 1
  fi
  PROXY_DOMAIN=$(getenv_file "$ETC/settings.env" PROXY_POOL_PROXY_DOMAIN)
  [[ -n $PROXY_DOMAIN ]] || { red 'PROXY_POOL_PROXY_DOMAIN пуст.'; return 1; }
  local resolved
  resolved=$(getent ahostsv4 "$PROXY_DOMAIN" 2>/dev/null | awk 'NR==1{print $1}')
  [[ -n $resolved ]] || { red "Не удалось резолвить $PROXY_DOMAIN в IPv4."; return 1; }
  ENTER_PUBLIC=$(ip -4 route get 1.1.1.1 2>/dev/null | sed -n 's/.* src \([^ ]*\).*/\1/p' | head -n1)
  if [[ -n $ENTER_PUBLIC && $resolved != "$ENTER_PUBLIC" ]]; then
    yellow "DNS $PROXY_DOMAIN -> $resolved, а исходящий IPv4 ENTER -> $ENTER_PUBLIC. Проверьте DNS перед клиентским тестом."
    yesno 'Продолжить несмотря на несовпадение DNS?' || return 1
  fi
  green "AWG: $ENTER_IP -> $EXIT_IP"
  green "Telemt config: $TELEMT_CONFIG"
  green "Public host: $PROXY_DOMAIN:443"
}

backup_all(){
  local ts
  ts=$(date +%s)
  NODE_BACKUP_DIR="$BACKUP_ROOT/$NODE_ID"
  install -d -m 700 "$NODE_BACKUP_DIR"
  TELEMT_BACKUP="$NODE_BACKUP_DIR/telemt.toml.$ts"
  rx "cp -a '$TELEMT_CONFIG' '$TELEMT_BACKUP'"
  HAPROXY_WAS_INSTALLED=0; dpkg-query -W -f='${Status}' haproxy 2>/dev/null | grep -q 'ok installed' && HAPROXY_WAS_INSTALLED=1 || true
  HAPROXY_WAS_ACTIVE=$(systemctl is-active haproxy 2>/dev/null || true)
  HAPROXY_BACKUP="$NODE_BACKUP_DIR/haproxy.cfg.$ts"
  [[ -f $HAPROXY_CONFIG ]] && cp -a "$HAPROXY_CONFIG" "$HAPROXY_BACKUP" || : > "$HAPROXY_BACKUP.absent"
  DP_STATE="$DP_STATE_DIR/$NODE_ID.state"
  save_state
}

save_state(){
  umask 077
  {
    printf 'NODE_ID=%q\n' "$NODE_ID"
    printf 'EXIT_HOST=%q\n' "$EXIT_HOST"
    printf 'EXIT_IP=%q\n' "$EXIT_IP"
    printf 'ENTER_IP=%q\n' "$ENTER_IP"
    printf 'LOCAL_IF=%q\n' "$LOCAL_IF"
    printf 'SSH_PORT=%q\n' "$SSH_PORT"
    printf 'SSH_KEY=%q\n' "$SSH_KEY"
    printf 'PROXY_DOMAIN=%q\n' "$PROXY_DOMAIN"
    printf 'TELEMT_CONFIG=%q\n' "$TELEMT_CONFIG"
    printf 'TELEMT_BACKUP=%q\n' "$TELEMT_BACKUP"
    printf 'HAPROXY_BACKUP=%q\n' "$HAPROXY_BACKUP"
    printf 'HAPROXY_WAS_INSTALLED=%q\n' "$HAPROXY_WAS_INSTALLED"
    printf 'HAPROXY_WAS_ACTIVE=%q\n' "$HAPROXY_WAS_ACTIVE"
  } > "$DP_STATE"
  chmod 600 "$DP_STATE"
}

patch_telemt(){
  cyan 'Telemt'
  rscript <<EOF
set -Eeuo pipefail
python3 - '$TELEMT_CONFIG' '$EXIT_IP' '$PROXY_DOMAIN' <<'PY'
from pathlib import Path
import json,re,sys
p=Path(sys.argv[1]); exit_ip=sys.argv[2]; public_host=sys.argv[3]
text=p.read_text(encoding='utf-8')
lines=text.splitlines()

def patch_section(lines, section, values):
    header=f'[{section}]'
    start=None
    for i,line in enumerate(lines):
        if line.strip()==header:
            start=i; break
    if start is None:
        if lines and lines[-1].strip(): lines.append('')
        lines.append(header)
        for k,v in values.items(): lines.append(f'{k} = {v}')
        return lines
    end=len(lines)
    for i in range(start+1,len(lines)):
        s=lines[i].strip()
        if s.startswith('[') and s.endswith(']'):
            end=i; break
    seen=set(); out=[]
    key_re={k:re.compile(r'^\\s*'+re.escape(k)+r'\\s*=') for k in values}
    for i,line in enumerate(lines):
        if start < i < end:
            matched=None
            for k,rx in key_re.items():
                if rx.match(line): matched=k; break
            if matched:
                if matched not in seen:
                    out.append(f'{matched} = {values[matched]}'); seen.add(matched)
                continue
        out.append(line)
    start2=next(i for i,l in enumerate(out) if l.strip()==header)
    end2=len(out)
    for i in range(start2+1,len(out)):
        s=out[i].strip()
        if s.startswith('[') and s.endswith(']'):
            end2=i; break
    missing=[k for k in values if k not in seen]
    if missing:
        out[end2:end2]=[f'{k} = {values[k]}' for k in missing]
    return out

lines=patch_section(lines,'server',{
    'port':'443',
    'listen_addr_ipv4':json.dumps(exit_ip),
    'proxy_protocol':'true',
})
lines=patch_section(lines,'general.links',{
    'public_host':json.dumps(public_host),
    'public_port':'443',
})
p.write_text('\\n'.join(lines)+'\\n',encoding='utf-8')
PY
systemctl restart telemt
sleep 2
systemctl is-active telemt >/dev/null
ss -ltnpH 'sport = :443' | grep -F '$EXIT_IP:443' >/dev/null
EOF
  green "Telemt теперь слушает $EXIT_IP:443 с PROXY protocol."
}

install_haproxy(){
  cyan 'HAProxy'
  apt-get update -y
  DEBIAN_FRONTEND=noninteractive apt-get install -y haproxy
  cat > "$HAPROXY_CONFIG" <<EOF
global
    log /dev/log local0
    maxconn 10000

defaults
    log global
    mode tcp
    option tcplog
    option clitcpka
    option srvtcpka
    timeout connect 5s
    timeout client 2h
    timeout server 2h
    timeout check 5s

frontend tyxe_mtproto_443
    bind 0.0.0.0:443
    maxconn 8000
    option tcp-smart-accept
    default_backend tyxe_telemt

backend tyxe_telemt
    option tcp-smart-connect
    server $NODE_ID $EXIT_IP:443 check inter 5s rise 2 fall 3 send-proxy-v2

EOF
  haproxy -c -f "$HAPROXY_CONFIG"
  systemctl enable haproxy >/dev/null
  systemctl restart haproxy
  sleep 2
  systemctl is-active haproxy >/dev/null
  ss -ltnpH 'sport = :443' | grep -q haproxy
  green "HAProxy слушает ENTER :443 -> $EXIT_IP:443 send-proxy-v2."
}

postcheck(){
  cyan 'Проверка'
  ping -c 2 -W 2 "$EXIT_IP" >/dev/null
  timeout 5 bash -c "</dev/tcp/$EXIT_IP/443" || { red 'TCP до Telemt через AWG недоступен.'; return 1; }
  systemctl is-active haproxy >/dev/null
  rx 'systemctl is-active telemt' | grep -qx active
  printf 'Public:   %s:443\n' "$PROXY_DOMAIN"
  printf 'ENTER:    0.0.0.0:443 (HAProxy)\n'
  printf 'Tunnel:   %s -> %s\n' "$ENTER_IP" "$EXIT_IP"
  printf 'EXIT:     %s:443 (Telemt + PROXY protocol)\n' "$EXIT_IP"
  green 'Dataplane базово готов. Следующий тест — подключение реального Telegram-клиента по ссылке Telemt.'
}

setup(){
  require_enter
  load_awg "${1:-}" || exit 1
  [[ ! -e "$DP_STATE_DIR/$NODE_ID.state" ]] || { red "Dataplane state уже существует для $NODE_ID. Сначала status/rollback."; exit 1; }
  preflight
  yellow 'После этого шага Telemt перестанет принимать прямые клиентские подключения на публичном IP EXIT:443.'
  yellow "Клиенты должны будут подключаться к $PROXY_DOMAIN:443 через ENTER."
  yesno 'Продолжить настройку dataplane?' || exit 0
  cyan 'Backup'; backup_all
  if ! patch_telemt; then red "Telemt patch не прошёл. Откат: sudo tyxe-dataplane rollback $NODE_ID"; exit 1; fi
  if ! install_haproxy; then red "HAProxy setup не прошёл. Откат: sudo tyxe-dataplane rollback $NODE_ID"; exit 1; fi
  postcheck || { red "Проверка не прошла. Откат: sudo tyxe-dataplane rollback $NODE_ID"; exit 1; }
}

load_dp_state(){
  require_enter
  local id="${1:-}" count
  if [[ -z $id ]]; then
    mapfile -t states < <(find "$DP_STATE_DIR" -maxdepth 1 -type f -name '*.state' -printf '%f\n' 2>/dev/null | sort)
    count=${#states[@]}
    (( count == 1 )) || { red 'Укажите node id.'; return 1; }
    id=${states[0]%.state}
  fi
  DP_STATE="$DP_STATE_DIR/$id.state"
  [[ -r $DP_STATE ]] || { red "Dataplane state не найден: $id"; return 1; }
  # shellcheck disable=SC1090
  . "$DP_STATE"
  TARGET="root@$EXIT_HOST"
  SSH=(-p "$SSH_PORT" -o ConnectTimeout=10 -o ServerAliveInterval=15 -o ServerAliveCountMax=2 -o ControlMaster=auto -o ControlPersist=120 -o ControlPath=/run/tyxe-dataplane-%C)
  if [[ -n ${SSH_KEY:-} ]]; then SSH+=(-i "$SSH_KEY"); fi
  return 0
}

status(){
  load_dp_state "${1:-}" || exit 1
  cyan "Dataplane status: $NODE_ID"
  printf 'Public host: %s:443\nTunnel: %s -> %s\n' "$PROXY_DOMAIN" "$ENTER_IP" "$EXIT_IP"
  systemctl status haproxy --no-pager -l || true
  printf '\n'; ss -ltnpH 'sport = :443' || true
  printf '\nEXIT Telemt:\n'; rx "systemctl status telemt --no-pager -l; ss -ltnpH 'sport = :443'" || true
}

rollback(){
  load_dp_state "${1:-}" || exit 1
  yesno "Откатить dataplane $NODE_ID?" || exit 0
  cyan 'Rollback HAProxy'
  systemctl stop haproxy 2>/dev/null || true
  if [[ -f $HAPROXY_BACKUP ]]; then
    install -Dm 644 "$HAPROXY_BACKUP" "$HAPROXY_CONFIG"
    [[ $HAPROXY_WAS_ACTIVE == active ]] && systemctl restart haproxy || true
  else
    rm -f "$HAPROXY_CONFIG"
    systemctl disable haproxy >/dev/null 2>&1 || true
  fi
  cyan 'Rollback Telemt'
  rx "install -Dm 600 '$TELEMT_BACKUP' '$TELEMT_CONFIG'; systemctl restart telemt"
  rm -f "$DP_STATE"
  green 'Dataplane откатан; AWG, Agent, Controller, пользователи Telemt и сертификаты не затронуты.'
}

case "${1:-setup}" in
  setup|install) shift; setup "${1:-}";;
  status) shift; status "${1:-}";;
  rollback|uninstall) shift; rollback "${1:-}";;
  *) echo 'Usage: tyxe-dataplane [setup [node-id]|status [node-id]|rollback [node-id]]' >&2; exit 2;;
esac
