#!/usr/bin/env bash
set -Eeuo pipefail

ETC=/etc/proxy-pool
SETTINGS=$ETC/settings.env
DP_STATE_DIR=$ETC/dataplane-nodes
STATE_FILE=$ETC/shared443.state
BACKUP_ROOT=/var/lib/proxy-pool/shared443
HAPROXY_CONFIG=/etc/haproxy/haproxy.cfg
NGINX_CONFIG=/etc/nginx/conf.d/tyxe-shared443.conf
SITE_ROOT=/var/www/proxy-pool-selfsteal
DECOY_PORT=8444
PANEL_TLS_PORT=8445

red(){ printf '\033[31m%s\033[0m\n' "$*" >&2; }
green(){ printf '\033[32m%s\033[0m\n' "$*"; }
yellow(){ printf '\033[33m%s\033[0m\n' "$*" >&2; }
cyan(){ printf '\n\033[1;36m== %s ==\033[0m\n' "$*"; }
yesno(){ local p="$1" v=''; read -r -p "$p [y/N]: " v </dev/tty || true; [[ "$v" =~ ^[yY]$ ]]; }
getenv_file(){ sed -n "s/^$2=//p" "$1" 2>/dev/null | tail -n1 | sed -e 's/^"//' -e 's/"$//' -e "s/^'//" -e "s/'$//"; }

[[ $EUID -eq 0 ]] || { red 'Запустите через sudo/root.'; exit 1; }

require_enter(){
  [[ -r $SETTINGS ]] || { red 'TYXE settings не найдены.'; return 1; }
  [[ "$(getenv_file "$SETTINGS" PROXY_POOL_ROLE)" == controller ]] || { red 'Shared-443 classifier ставится только на ENTER/controller.'; return 1; }
  systemctl is-active --quiet haproxy || { red 'HAProxy не active. Сначала должен работать dataplane.'; return 1; }
  systemctl is-active --quiet nginx || { red 'nginx не active.'; return 1; }
}

choose_dp_state(){
  local requested="${1:-}" count
  if [[ -n $requested ]]; then
    DP_STATE="$DP_STATE_DIR/$requested.state"
    [[ -r $DP_STATE ]] || { red "Dataplane state не найден: $requested"; return 1; }
    return 0
  fi
  mapfile -t _states < <(find "$DP_STATE_DIR" -maxdepth 1 -type f -name '*.state' -printf '%f\n' 2>/dev/null | sort)
  count=${#_states[@]}
  (( count == 1 )) || { red 'Укажите node id: tyxe-shared443 setup <node-id>'; return 1; }
  DP_STATE="$DP_STATE_DIR/${_states[0]}"
}

load_dp(){
  choose_dp_state "${1:-}" || return 1
  # Root-owned state generated by TYXE dataplane.
  # shellcheck disable=SC1090
  . "$DP_STATE"
  : "${NODE_ID:?}" "${EXIT_HOST:?}" "${EXIT_IP:?}" "${TELEMT_CONFIG:?}"
  SSH_PORT=${SSH_PORT:-22}; SSH_KEY=${SSH_KEY:-}
  TARGET="root@$EXIT_HOST"
  SSH=(-p "$SSH_PORT" -o ConnectTimeout=10 -o ServerAliveInterval=15 -o ServerAliveCountMax=2 -o ControlMaster=auto -o ControlPersist=120 -o ControlPath=/run/tyxe-shared443-%C)
  if [[ -n $SSH_KEY ]]; then SSH+=(-i "$SSH_KEY"); fi
  return 0
}
rx(){ ssh "${SSH[@]}" "$TARGET" "$@"; }

read_fake_sni(){
  FAKE_SNI=$(rx "python3 - '$TELEMT_CONFIG' <<'PY'
from pathlib import Path
import re,sys
p=Path(sys.argv[1])
text=p.read_text(encoding='utf-8',errors='replace')
try:
    import tomllib
    d=tomllib.loads(text)
    v=str(d.get('censorship',{}).get('tls_domain','')).strip().rstrip('.').lower()
    if v:
        print(v); raise SystemExit
except Exception:
    pass
in_sec=False
for raw in text.splitlines():
    s=raw.strip()
    if s.startswith('[') and s.endswith(']'):
        in_sec=(s=='[censorship]'); continue
    if in_sec:
        m=re.match(r'tls_domain\\s*=\\s*[\"\x27]([^\"\x27]+)[\"\x27]',s)
        if m:
            print(m.group(1).strip().rstrip('.').lower()); raise SystemExit
raise SystemExit(2)
PY") || { red 'Не удалось прочитать [censorship] tls_domain из Telemt.'; return 1; }
  [[ $FAKE_SNI =~ ^[A-Za-z0-9.-]+$ && $FAKE_SNI == *.* ]] || { red "Некорректный Telemt tls_domain: $FAKE_SNI"; return 1; }
}

cert_dir(){
  local d="$1"
  if [[ -s "/var/lib/tyxe-pool-persistent/letsencrypt/live/$d/fullchain.pem" && -s "/var/lib/tyxe-pool-persistent/letsencrypt/live/$d/privkey.pem" ]]; then
    printf '/var/lib/tyxe-pool-persistent/letsencrypt/live/%s' "$d"; return 0
  fi
  if [[ -s "/etc/letsencrypt/live/$d/fullchain.pem" && -s "/etc/letsencrypt/live/$d/privkey.pem" ]]; then
    printf '/etc/letsencrypt/live/%s' "$d"; return 0
  fi
  return 1
}

port_free_or_nginx(){
  local p="$1" holder
  holder=$(ss -ltnpH "sport = :$p" 2>/dev/null || true)
  [[ -z $holder ]] && return 0
  grep -q nginx <<<"$holder"
}

preflight(){
  cyan 'Preflight shared TCP/443'
  [[ ! -e $STATE_FILE ]] || { red 'Shared-443 state уже существует. Используйте status/rollback.'; return 1; }
  grep -q '^frontend tyxe_mtproto_443$' "$HAPROXY_CONFIG" || { red 'Не найден TYXE frontend tyxe_mtproto_443; чужой HAProxy автоматически не меняем.'; return 1; }
  grep -q '^backend tyxe_telemt$' "$HAPROXY_CONFIG" || { red 'Не найден TYXE backend tyxe_telemt.'; return 1; }
  ! grep -q '^backend tyxe_https_decoy$' "$HAPROXY_CONFIG" || { red 'Classifier backend уже присутствует в HAProxy.'; return 1; }

  PROXY_DOMAIN=$(getenv_file "$SETTINGS" PROXY_POOL_PROXY_DOMAIN)
  PANEL_DOMAIN=$(getenv_file "$SETTINGS" PROXY_POOL_PANEL_DOMAIN)
  PANEL_PORT=$(getenv_file "$SETTINGS" PROXY_POOL_PORT); PANEL_PORT=${PANEL_PORT:-9101}
  [[ -n $PROXY_DOMAIN ]] || { red 'PROXY_POOL_PROXY_DOMAIN пуст.'; return 1; }
  read_fake_sni
  [[ $FAKE_SNI != "$PROXY_DOMAIN" ]] || { red "Telemt tls_domain совпадает с proxy domain ($PROXY_DOMAIN): SNI-классификация невозможна."; return 1; }
  [[ -z $PANEL_DOMAIN || $FAKE_SNI != "$PANEL_DOMAIN" ]] || { red "Telemt tls_domain совпадает с panel domain ($PANEL_DOMAIN): SNI-классификация невозможна."; return 1; }

  PROXY_CERT=$(cert_dir "$PROXY_DOMAIN") || { red "Нет валидных файлов сертификата для $PROXY_DOMAIN. Shared HTTPS пока включать нельзя."; return 1; }
  PANEL_ENABLED=0; PANEL_CERT=''
  if [[ -n $PANEL_DOMAIN ]] && PANEL_CERT=$(cert_dir "$PANEL_DOMAIN"); then PANEL_ENABLED=1; else yellow 'Отдельный HTTPS panel backend не включён: panel domain/certificate отсутствует.'; fi

  port_free_or_nginx "$DECOY_PORT" || { red "TCP/$DECOY_PORT занят не nginx."; return 1; }
  if (( PANEL_ENABLED )); then port_free_or_nginx "$PANEL_TLS_PORT" || { red "TCP/$PANEL_TLS_PORT занят не nginx."; return 1; }; fi

  green "Telegram FakeTLS SNI: $FAKE_SNI -> Telemt $EXIT_IP:443"
  green "HTTPS site SNI:       $PROXY_DOMAIN -> nginx 127.0.0.1:$DECOY_PORT"
  if (( PANEL_ENABLED )); then green "HTTPS panel SNI:      $PANEL_DOMAIN -> nginx 127.0.0.1:$PANEL_TLS_PORT -> Controller :$PANEL_PORT"; fi
  yellow 'Любой другой TLS SNI и трафик без распознанного FakeTLS SNI по умолчанию уйдёт на сайт-заглушку, а не в Telemt.'
}

backup_all(){
  local ts; ts=$(date +%s)
  BACKUP_DIR="$BACKUP_ROOT/$ts"
  install -d -m 700 "$BACKUP_DIR"
  HAPROXY_BACKUP="$BACKUP_DIR/haproxy.cfg"; cp -a "$HAPROXY_CONFIG" "$HAPROXY_BACKUP"
  NGINX_BACKUP=''
  if [[ -e $NGINX_CONFIG || -L $NGINX_CONFIG ]]; then NGINX_BACKUP="$BACKUP_DIR/tyxe-shared443.conf"; cp -a "$NGINX_CONFIG" "$NGINX_BACKUP"; fi
  INDEX_CREATED=0
  if [[ ! -e $SITE_ROOT/index.html ]]; then
    install -d -m 755 "$SITE_ROOT"
    cat > "$SITE_ROOT/index.html" <<'HTML'
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Welcome</title></head><body><main><h1>Welcome</h1><p>This website is currently under construction.</p></main></body></html>
HTML
    INDEX_CREATED=1
  fi
  save_state
}

save_state(){
  umask 077
  {
    printf 'NODE_ID=%q\n' "$NODE_ID"
    printf 'FAKE_SNI=%q\n' "$FAKE_SNI"
    printf 'PROXY_DOMAIN=%q\n' "$PROXY_DOMAIN"
    printf 'PANEL_DOMAIN=%q\n' "$PANEL_DOMAIN"
    printf 'PANEL_PORT=%q\n' "$PANEL_PORT"
    printf 'PANEL_ENABLED=%q\n' "$PANEL_ENABLED"
    printf 'PROXY_CERT=%q\n' "$PROXY_CERT"
    printf 'PANEL_CERT=%q\n' "$PANEL_CERT"
    printf 'HAPROXY_BACKUP=%q\n' "$HAPROXY_BACKUP"
    printf 'NGINX_BACKUP=%q\n' "$NGINX_BACKUP"
    printf 'INDEX_CREATED=%q\n' "$INDEX_CREATED"
  } > "$STATE_FILE"
  chmod 600 "$STATE_FILE"
}

write_nginx(){
  cyan 'nginx loopback TLS backends'
  cat > "$NGINX_CONFIG" <<EOF
server {
    listen 127.0.0.1:$DECOY_PORT ssl;
    server_name $PROXY_DOMAIN;
    ssl_certificate $PROXY_CERT/fullchain.pem;
    ssl_certificate_key $PROXY_CERT/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    root $SITE_ROOT;
    index index.html;
    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options DENY always;
    location / { try_files \$uri \$uri/ /index.html; }
}
EOF
  if (( PANEL_ENABLED )); then
    cat >> "$NGINX_CONFIG" <<EOF

server {
    listen 127.0.0.1:$PANEL_TLS_PORT ssl;
    server_name $PANEL_DOMAIN;
    ssl_certificate $PANEL_CERT/fullchain.pem;
    ssl_certificate_key $PANEL_CERT/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options DENY always;
    add_header Referrer-Policy no-referrer always;
    location / {
        proxy_pass http://127.0.0.1:$PANEL_PORT;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-Proto https;
    }
}
EOF
  fi
  nginx -t
  systemctl reload nginx
  ss -ltnpH "sport = :$DECOY_PORT" | grep -q nginx
  if (( PANEL_ENABLED )); then ss -ltnpH "sport = :$PANEL_TLS_PORT" | grep -q nginx; fi
}

patch_haproxy(){
  cyan 'HAProxy SNI classifier'
  python3 - "$HAPROXY_CONFIG" "$FAKE_SNI" "$PROXY_DOMAIN" "$PANEL_DOMAIN" "$PANEL_ENABLED" "$DECOY_PORT" "$PANEL_TLS_PORT" <<'PY'
from pathlib import Path
import re,sys
p=Path(sys.argv[1]); fake,proxy,panel=sys.argv[2:5]; panel_on=sys.argv[5]=='1'; decoy=sys.argv[6]; panel_port=sys.argv[7]
lines=p.read_text().splitlines()
section=re.compile(r'^(global|defaults|frontend|backend|listen|peers|resolvers|userlist|cache|program|mailers|ring)\\b')
start=None
for i,l in enumerate(lines):
    if l.strip()=='frontend tyxe_mtproto_443': start=i; break
if start is None: raise SystemExit('TYXE frontend not found')
end=len(lines)
for i in range(start+1,len(lines)):
    if section.match(lines[i]) and not lines[i].startswith((' ','\\t')):
        end=i; break
if any(l.strip()=='backend tyxe_https_decoy' for l in lines): raise SystemExit('classifier backend already exists')
front=[
'frontend tyxe_mtproto_443',
'    bind 0.0.0.0:443',
'    maxconn 8000',
'    option tcp-smart-accept',
'    tcp-request inspect-delay 3s',
'    tcp-request content accept if { req_ssl_hello_type 1 }',
f'    acl tyxe_mtproto_sni req.ssl_sni -i {fake}',
f'    acl tyxe_proxy_sni req.ssl_sni -i {proxy}',
]
if panel_on: front.append(f'    acl tyxe_panel_sni req.ssl_sni -i {panel}')
front.append('    use_backend tyxe_telemt if tyxe_mtproto_sni')
if panel_on: front.append('    use_backend tyxe_https_panel if tyxe_panel_sni')
front += ['    use_backend tyxe_https_decoy if tyxe_proxy_sni','    default_backend tyxe_https_decoy','']
lines[start:end]=front
while lines and not lines[-1].strip(): lines.pop()
lines += ['', 'backend tyxe_https_decoy', '    option tcp-smart-connect', f'    server tyxe_decoy 127.0.0.1:{decoy} check inter 5s rise 2 fall 3']
if panel_on:
    lines += ['', 'backend tyxe_https_panel', '    option tcp-smart-connect', f'    server tyxe_panel 127.0.0.1:{panel_port} check inter 5s rise 2 fall 3']
p.write_text('\n'.join(lines)+'\n')
PY
  haproxy -c -f "$HAPROXY_CONFIG"
  systemctl reload haproxy
  sleep 1
  systemctl is-active --quiet haproxy
}

postcheck(){
  cyan 'Проверка'
  haproxy -c -f "$HAPROXY_CONFIG"
  nginx -t
  local code
  code=$(curl --noproxy '*' -sS --resolve "$PROXY_DOMAIN:443:127.0.0.1" -o /dev/null -w '%{http_code}' "https://$PROXY_DOMAIN/" || true)
  [[ $code =~ ^(200|301|302|304)$ ]] || { red "HTTPS decoy check failed: HTTP ${code:-none}"; return 1; }
  green "https://$PROXY_DOMAIN/ -> HTTP $code"
  if (( PANEL_ENABLED )); then
    code=$(curl --noproxy '*' -sS --resolve "$PANEL_DOMAIN:443:127.0.0.1" -o /dev/null -w '%{http_code}' "https://$PANEL_DOMAIN/" || true)
    [[ $code =~ ^(200|301|302|303|401|403)$ ]] || { red "HTTPS panel check failed: HTTP ${code:-none}"; return 1; }
    green "https://$PANEL_DOMAIN/ -> HTTP $code"
  fi
  green "Classifier active: FakeTLS $FAKE_SNI -> Telemt; остальные TLS -> selfsteal nginx."
  yellow 'Теперь обязательно проверьте существующую Telegram-ссылку по Wi-Fi и мобильной сети.'
}

setup(){
  require_enter
  load_dp "${1:-}" || return 1
  preflight
  yesno 'Включить shared-443 classifier/selfsteal?' || return 0
  cyan 'Backup'; backup_all
  if ! write_nginx; then red 'nginx setup failed. Запустите: sudo tyxe-shared443 rollback'; return 1; fi
  if ! patch_haproxy; then red 'HAProxy classifier failed. Запустите: sudo tyxe-shared443 rollback'; return 1; fi
  postcheck || { red 'Postcheck failed. Запустите: sudo tyxe-shared443 rollback'; return 1; }
}

status(){
  require_enter
  cyan 'Shared TCP/443 status'
  if [[ ! -r $STATE_FILE ]]; then yellow 'Classifier state не найден.'; return 0; fi
  # shellcheck disable=SC1090
  . "$STATE_FILE"
  printf 'FakeTLS SNI: %s\nProxy site:   %s\n' "$FAKE_SNI" "$PROXY_DOMAIN"
  (( PANEL_ENABLED )) && printf 'Panel:        %s\n' "$PANEL_DOMAIN"
  printf '\nHAProxy: '; systemctl is-active haproxy || true
  printf 'nginx:   '; systemctl is-active nginx || true
  printf '\nListeners:\n'; ss -ltnp | grep -E ":(443|$DECOY_PORT|$PANEL_TLS_PORT)\\b" || true
  printf '\nClassifier ACLs:\n'; grep -E 'tyxe_(mtproto|proxy|panel)_sni|default_backend tyxe_https_decoy' "$HAPROXY_CONFIG" || true
}

rollback(){
  require_enter
  [[ -r $STATE_FILE ]] || { yellow 'Classifier state не найден.'; return 0; }
  # shellcheck disable=SC1090
  . "$STATE_FILE"
  yesno 'Откатить shared-443 classifier и вернуть предыдущий HAProxy?' || return 0
  [[ -s $HAPROXY_BACKUP ]] || { red 'HAProxy backup отсутствует.'; return 1; }
  cp -a "$HAPROXY_BACKUP" "$HAPROXY_CONFIG"
  if [[ -n ${NGINX_BACKUP:-} && -s $NGINX_BACKUP ]]; then cp -a "$NGINX_BACKUP" "$NGINX_CONFIG"; else rm -f "$NGINX_CONFIG"; fi
  [[ ${INDEX_CREATED:-0} == 1 ]] && rm -f "$SITE_ROOT/index.html" || true
  nginx -t
  haproxy -c -f "$HAPROXY_CONFIG"
  systemctl reload nginx
  systemctl reload haproxy
  rm -f "$STATE_FILE"
  green 'Shared-443 classifier откатан. Dataplane/AWG/Telemt/MTProxyL не изменены.'
}

case "${1:-status}" in
  setup|install) shift; setup "${1:-}";;
  status) status;;
  rollback|remove|uninstall) rollback;;
  *) echo 'Usage: tyxe-shared443 [setup [node-id]|status|rollback]' >&2; exit 2;;
esac
